### ISSUE TITLE
How do I build this for iPadOS

### ISSUE THREAD

**Issue by murasu** [1998code/SwiftUI2-MacSidebar#1]
Hi, Thank you for this demo. It helped me get started with my SwiftUI 2 app for macOS.  

How will I build the same app for iPadOS, though. The SidebarView is only targeted at macOS.  

Appreciate some pointers. Thank you.

**Comment by 1998code** [comment]
For iPadOS,
use:

NavigationView {
            List {
                // Example
                NavigationLink(destination: DemoView()) {
                    Label("Demo", systemImage: "square.grid.3x2.fill")
                }
                NavigationLink(destination: DemosView()) {
                    Label("Demos", systemImage: "books.vertical")
                }
                // add more...

            }
            .listStyle(SidebarListStyle())  // Sidebar List Style for iOS
            .navigationTitle("Title")          // Nav Title
            
            // Default View you want to show on iPad
            DefaultView()
}

**Comment by 1998code** [comment]
Use #if os(iOS) and #else to divide iOS/macOS if needed.

**Comment by murasu** [comment]
Thank you! Works beautifully.

**Comment by murasu** [comment]
Sorry, It worked very well on iOS. When I returned to macOS, I am having some issues. I am very new to SwiftUI. Pardon the question if it's trivial. How do I prevent this error?

<img width="707" alt="image" src="https://user-images.githubusercontent.com/22926756/91972841-d5981500-ed4d-11ea-82e9-19568fcc5519.png">

**Comment by 1998code** [comment]
Hey, @murasu you cannot perform your code in that way. 
Try Separate the code first:
#if os(iOS)
// For iPad
#else
//For macOS
#endif

In SwiftUI, it will not work if you put #if statement between .navigationTitle and .toolbar or after line54;

Let's say, you may use:
#if os(iOS)
DemoView()
#else
DemoView()
.toolbar {
 // ...
#endif

Then, put the list inside "DemoView()".

**Comment by murasu** [comment]
Lovely! Thank you so much.
