### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by josepvcliment** [1998code/SwiftUI2-MacSidebar#3]
When I try to build your project says "Cannot find "SidebarView" in scope" in SidebarApp.swift

**Comment by 1998code** [comment]
Please check:
 
<img width="243" alt="截圖 2021-02-02 下午7 35 06" src="https://user-images.githubusercontent.com/54872601/106594923-c2ec6b00-658d-11eb-8476-5aa747426996.png">

<img width="259" alt="截圖 2021-02-02 下午7 35 38" src="https://user-images.githubusercontent.com/54872601/106594981-d4ce0e00-658d-11eb-8348-d0b09fdd6f8b.png">

"SidebarView" is inside SidebarView.swift.

**Comment by josepvcliment** [comment]
Solved, thank you!
